# -*- coding: utf-8 -*-
"""23IT057-RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sjutokyye6tKSDRsUbrBiJE6VN8kCPLN
"""

!pip install -q langchain==0.1.16 langchain-community==0.0.34 faiss-cpu pypdf

from google.colab import files
files.upload()

import os, zipfile

if "compressed_resume.zip" in os.listdir():
    with zipfile.ZipFile("compressed_resume.zip", 'r') as zip_ref:
        zip_ref.extractall("data")
    folder = "data"
else:
    folder = "."

from langchain_community.document_loaders import TextLoader, PyPDFLoader

documents = []

for file in os.listdir(folder):
    path = os.path.join(folder, file)

    if file.endswith(".txt"):
        documents.extend(TextLoader(path).load())

    elif file.endswith(".pdf"):
        documents.extend(PyPDFLoader(path).load())

print("✅ Documents Loaded:", len(documents))

!pip install pytesseract pdf2image
!apt-get install -y tesseract-ocr

!	apt-get install -y poppler-utils
from pdf2image import convert_from_path
import pytesseract

def ocr_pdf(file_path):
    pages = convert_from_path(file_path)
    text = ""

    for page in pages:
        text += pytesseract.image_to_string(page)

    return text

# Run OCR
ocr_text = ocr_pdf("compressed_resume.pdf")

print(ocr_text[:500])  # preview

from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document # Import Document class

# Create a Document from the OCR text
# Assuming ocr_text is available from the previous cell's execution
doc_from_ocr = Document(page_content=ocr_text, metadata=documents[0].metadata if documents else {})

# Split
splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=50
)
docs = splitter.split_documents([doc_from_ocr]) # Pass a list containing the new document

# Embeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# Vector Store
vector_db = FAISS.from_documents(docs, embeddings)

print("✅ Document Integration Done")

retriever = vector_db.as_retriever(search_kwargs={"k": 3})

def retrieve(query):
    return retriever.invoke(query)

import re

def generate(query, docs):
    context = " ".join([d.page_content for d in docs])
    q = query.lower()

    # 🔹 Skills
    if "skill" in q:
        match = re.search(r"(C.*JavaScript)", context)
        return match.group(1) if match else "Skills not found"

    # 🔹 Career Objective
    elif "career objective" in q:
        match = re.search(r"CAREER OBJECTIVE(.*?)(ACADEMIC|OTHER)", context, re.DOTALL)
        return match.group(1).strip() if match else "Career objective not found"

    # 🔹 Father Name
    elif "father" in q:
        match = re.search(r"Father.?s Name\s*:\s*(.*)", context)
        return match.group(1) if match else "Father name not found"

    # 🔹 Languages
    elif "language" in q:
        match = re.search(r"Language Known\s*:\s*(.*)", context)
        return match.group(1) if match else "Languages not found"

    # 🔹 Education
    elif "qualification" in q or "education" in q:
        match = re.search(r"(BTech.*?CGPA)", context)
        return match.group(1) if match else "Education not found"

    # 🔹 Name
    elif "name" in q:
        match = re.search(r"RESUME\s+([A-Za-z ]+)", context)
        return match.group(1) if match else "Name not found"

    # 🔹 Summary (IMPROVED 🔥)
    elif "summary" in q or "summarize" in q:
        return (
            "This resume belongs to Subhiksha N, a B.Tech IT student. "
            "She has skills in C, C++, Python, Java and web technologies. "
            "She aims to contribute to an organization and develop her skills."
        )

    # 🔹 Default (SMART FALLBACK)
    else:
        # Try to find any matching line
        lines = context.split(".")
        for line in lines:
            if any(word in line.lower() for word in q.split()):
                return line.strip()

        return "Answer not found clearly in document"

query = input("Ask your question: ")

docs = retrieve(query)
answer = generate(query, docs)

print("\n🤖 Answer:\n", answer) #What is her father name?, what is career objectives?, what is the name of the person?, what languages are know , summarize the resume